name: 'react to cordova'
description: 'Prepare cordova src from react'
inputs:
  build-dir:
    description: 'Folder where the react app build is located'
    required: false
    default: 'dist'
runs:
  using: 'node16'
  main: 'dist/index.js'