name: 'react to cordova'
description: 'Prepare cordova src from react'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'node16'
  main: 'dist/index.js'